# Generated by Django 3.1.6 on 2021-03-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
