# Generated by Django 3.1.6 on 2021-03-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_watchlist_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='count',
        ),
    ]
