# Generated by Django 3.1.6 on 2021-03-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_watchlist_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
