# Generated by Django 3.1.6 on 2021-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
