# Generated by Django 3.1.6 on 2021-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='img_url',
            field=models.CharField(default='No Image', max_length=1000),
        ),
    ]
