# Generated by Django 3.1.6 on 2021-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listings_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='img_url',
            field=models.CharField(default='No Image', max_length=10000),
        ),
    ]
