# Generated by Django 3.1.6 on 2021-03-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listings',
            name='item_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_price',
            field=models.FloatField(default=0.0),
        ),
    ]
