# Generated by Django 3.1.6 on 2021-03-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210309_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.FloatField(default=models.FloatField(default=0.0)),
        ),
    ]
