# Generated by Django 3.1.6 on 2021-03-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210309_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='img',
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('F', 'Fashion'), ('T', 'Toys'), ('E', 'Electronics'), ('H', 'Home'), ('A', 'Antique'), ('O', 'Wine')], default='NAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='listings',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
