# Generated by Django 3.1.6 on 2021-03-09 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210310_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='item_description',
            field=models.TextField(default='No Description', max_length=10000),
        ),
    ]
